fix bug of Query.merge, use the internal commom lib

diff --git a/control b/control
--- a/control
+++ b/control
@@ -1,9 +1,6 @@
 #!/bin/bash
-
-WORKSPACE=$(cd $(dirname $0)/; pwd)
-cd $WORKSPACE
-
-mkdir -p var
+workspace=$(cd $(dirname $0) && pwd)
+cd $workspace
 
 module=graph
 app=falcon-$module
@@ -11,9 +8,99 @@ conf=cfg.json
 pidfile=var/app.pid
 logfile=var/app.log
 
-[[ -f $module ]] && mv $module $app
-[[ -f $conf ]] || cp cfg.example.json $conf
+mkdir -p var &>/dev/null
 
+
+## build & pack
+function build() {
+    commit=$(git log -1 --pretty=%h)
+    cat <<EOF > ./g/git.go
+package g
+const (
+    COMMIT = "$commit"
+)
+EOF
+    go build -o $app main.go
+    sc=$?
+    if [ $sc -ne 0 ];then
+        echo "build error"
+        exit $sc
+    else
+        echo -n "build ok, vsn=" 
+        ./$app -v 
+    fi
+}
+
+function pack() {
+    build
+    git log -1 --pretty=%h > gitversion
+    version=`./$app -v`
+    tar zcvf $app-$version.tar.gz control $app cfg.example.json gitversion ./test/debug
+    rm -f gitversion &>/dev/null
+}
+
+function packbin() {
+    build
+    git log -1 --pretty=%h > gitversion
+    version=`./$app -v`
+    tar zcvf $app-bin-$version.tar.gz $app gitversion
+    rm -f gitversion &>/dev/null
+}
+
+## opt
+function start() {
+    check_pid
+    running=$?
+    if [ $running -gt 0 ];then
+        echo -n "started, pid="
+        cat $pidfile
+        return 1
+    fi
+
+    nohup ./$app -c $conf >>$logfile 2>&1 &
+    echo $! > $pidfile
+    echo "start ok, pid=$!"
+}
+
+function stop() {
+    pid=`cat $pidfile`
+    kill $pid
+    echo "stoped"
+}
+
+function shutdown() {
+    pid=`cat $pidfile`
+    kill -9 $pid
+    echo "stoped"
+}
+
+function restart() {
+    stop
+    sleep 1
+    start
+}
+
+## other
+function status() {
+    check_pid
+    running=$?
+    if [ $running -gt 0 ];then
+        echo -n "running, pid="
+        cat $pidfile
+    else
+        echo "stoped"
+    fi
+}
+
+function version() {
+    ./$app -vg
+}
+
+function tailf() {
+    tail -f $logfile
+}
+
+## internal
 function check_pid() {
     if [ -f $pidfile ];then
         pid=`cat $pidfile`
@@ -25,130 +112,48 @@ function check_pid() {
     return 0
 }
 
-function start() {
-    check_pid
-    running=$?
-    if [ $running -gt 0 ];then
-        echo -n "$app now is running already, pid="
-        cat $pidfile
-        return 1
-    fi
-
-    nohup ./$app -c $conf >>$logfile 2>&1 &
-    echo $! > $pidfile
-    echo "$app started..., pid=$!"
+## usage
+function usage() {
+    echo "$0 build|pack|packbin|start|stop|restart|status|tail|version"
 }
 
-function stop() {
-    pid=`cat $pidfile`
-    kill $pid
-    echo "$app quit..."
-}
-
-function shutdown() {
-    pid=`cat $pidfile`
-    kill -9 $pid
-    echo "$app kill..."
-}
-
-function kill9() {
-    pid=`cat $pidfile`
-    kill -9 $pid
-    echo "$app stoped..."
-}
-
-function restart() {
-	stop
-	sleep 2
-	start
-}
-
-function status() {
-    check_pid
-    running=$?
-    if [ $running -gt 0 ];then
-        echo -n "$app now is running, pid="
-        cat $pidfile
-		echo 
-    else
-        echo "$app is stoped"
-    fi
-}
-
-function tailf() {
-    tail -f $logfile
-}
-
-function help() {
-    echo "$0 start|stop|restart|status|tail|test"
-}
-
-function pack() {
-    build
-    git log -1 --pretty=%h > gitversion
-    version=`./$app -v`
-    tar zcvf $app-$version.tar.gz control $app cfg.example.json gitversion ./test/debug 
-}
-
-function packbin() {
-    build
-    git log -1 --pretty=%h > gitversion
-    version=`./$app -v`
-    tar zcvf $app-$version.tar.gz control $app gitversion
-}
-
-
-function build() {
-	commit=$(git log -1 --pretty=%h)
-	cat <<EOF > ./g/git.go
-package g
-const (
-	COMMIT = "$commit"
-)
-EOF
-    go build -o $app main.go
-    show_version
-}
-
-function show_version() {
-    ./$app -vg
-}
-
-function test() {
-    pkg=$1
-    if [ "X$pkg" != "X" ]; then
-        go test -v "github.com/open-falcon/$module/$pkg"
-    else
-        echo "test: bad args"
-    fi
-}
-
-if [ "$1" == "" ]; then
-    help
-elif [ "$1" == "stop" ];then
-    stop
-elif [ "$1" == "kill9" ];then
-    kill9
-elif [ "$1" == "start" ];then
-    start
-elif [ "$1" == "restart" ];then
-    restart
-elif [ "$1" == "status" ];then
-    status
-elif [ "$1" == "tail" ];then
-    tailf
-elif [ "$1" == "pack" ];then
-    pack
-elif [ "$1" == "packbin" ];then
-    packbin
-elif [ "$1" == "build" ];then
-    build
-elif [ "$1" == "version" ];then
-    show_version
-elif [ "$1" == "test" ]; then
-    test $2
-elif [ "$1" == "shutdown" ]; then
-    kill
-else
-    help
-fi
+## main
+action=$1
+case $action in
+    ## build
+    "build" )
+        build
+        ;;
+    "pack" )
+        pack
+        ;;
+    "packbin" )
+        packbin
+        ;;
+    ## opt
+    "start" )
+        start
+        ;;
+    "stop" )
+        stop
+        ;;
+    "kill" )
+        shutdown
+        ;;
+    "restart" )
+        restart
+        ;;
+    ## other
+    "status" )
+        status
+        ;;
+    "version" )
+        version
+        ;;
+    "tail" )
+        tailf
+        ;;
+    * )
+        usage
+        ;;
+esac
